# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2f0573a2625fbc701d1dc774a2329d3afc326b3079ccc76b7234a9bd86ff87ee792201daec48afafedf8e6ff0b49ad40aef601f555f9fab164388b71b491f94

test:
  secret_key_base: 84d56f41202ada22049ebae6c722fc5790f0a3080c8ddc88c27f788e4d6173f19f34374b667fad11f49b00a68bd19e0d78afdbc1335d5977d99dd203fd58b630

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
